### ISSUE TITLE
VSCode sync

### ISSUE THREAD

**Issue by hackhowtofaq** [castwide/atom-solargraph#1]
Hi, 

VSCode version is working like a charm!

Are you planning to sync this version with VSCode version?

Ty!

**Comment by castwide** [comment]
Thanks!

I definitely plan to update the Atom version. It might never be an exact duplicate of the VSCode extension due to differences in the frameworks, but I still want it to be a useful package.

The next step is to update its version of [solargraph-utils](https://github.com/castwide/solargraph-utils), which is the same NPM package that the VSCode extension uses to integrate with the gem. (Atom uses solargraph-utils 0.1.0 and VSCode uses 0.2.0.)

**Comment by hackhowtofaq** [comment]
Thanks! Great job!

**Comment by hackhowtofaq** [comment]
On more thing, 

since I am not happy with the vim ruby omnicomplete,  I ll try to create a vim plugin wrapper for your gem.

I ll post any progress in the solargraph gem page.

**Comment by hackhowtofaq** [comment]
I think the first ALPHA prototype is working! 
I' ll upload the code after a cleanup @ [hackhowtofaq/vim-solargraph](https://github.com/hackhowtofaq/vim-solargraph)

**Comment by castwide** [comment]
Glad to see it! I'll provide any support I can if you have any questions, and please feel free to report gem-related bugs at https://github.com/castwide/solargraph
